stages:
    - build
    - deploy

build:
    image: python:3.8
    stage: build
    script:
    - echo "Building..."
    - pip install -r requirements.txt
    artifacts:
        paths:
            - build/

pages:
  stage: deploy
  script:
    - mkdir public/
    - cp -r * public/
    - mv docs/ public/
  artifacts:
    paths:
      - public/
  only:
    - master

