stages:
    - build
    - test

build:
    image: python:3.8
    stage: build
    script:
    - echo "Building..."
    - pip install -r requirements.txt
    artifacts:
        paths:
            - build/

test:
    image: python:3.8
    stage: test
    script:
        - echo "Testing..."
